name: Create Pull Request from Submission

on:
  push:
    branches:
      - main

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Parse README for PR Content
        id: pr_content
        run: |
          README_FILE=$(find . -type f -name "README.md" -print -quit)

          if [[ -z "$README_FILE" ]]; then
            echo "README.md 파일을 찾을 수 없습니다."
            exit 1
          fi

          PR_TITLE=$(head -n 1 "$README_FILE" | sed 's/# //g' || true)
          LINK_SECTION=$(grep '\[문제 링크\]' "$README_FILE" || true)
          PERF_SECTION=$(grep -A 1 '### 성능 요약' "$README_FILE" || true)
          CATEGORY_SECTION=$(grep -A 1 '### 분류' "$README_FILE" || true)
          DATE_SECTION=$(grep -A 1 '### 제출 일자' "$README_FILE" || true)

          PR_BODY=""

          if [[ -n "$LINK_SECTION" ]]; then
            PR_BODY+="${LINK_SECTION}\n\n"
          fi
          if [[ -n "$PERF_SECTION" ]]; then
            PR_BODY+="${PERF_SECTION}\n\n"
          fi
          if [[ -n "$CATEGORY_SECTION" ]]; then
            PR_BODY+="${CATEGORY_SECTION}\n\n"
          fi
          if [[ -n "$DATE_SECTION" ]]; then
            PR_BODY+="${DATE_SECTION}\n"
          fi
          
          {
            echo 'body<<EOF'
            echo "${PR_BODY}"
            echo 'EOF'
          } >> "$GITHUB_OUTPUT"

          echo "title=${PR_TITLE}" >> "$GITHUB_OUTPUT"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "백준 문제 풀이 자동 업데이트"
          title: ${{ steps.pr_content.outputs.title }}
          body: ${{ steps.pr_content.outputs.body }}
          base: complete
          branch: main
          delete-branch: false