name: Create Pull Request from Submission

on:
  push:
    branches:
      - main

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      # 1. 리포지토리 코드를 가져옵니다.
      - name: Checkout code
        uses: actions/checkout@v3
          
          # 2. README.md 파일을 파싱하여 PR 제목과 본문을 준비합니다. (⭐️ 방어 코드 추가 버전)
                - name: Parse README for PR Content
                id: pr_content
                run: |
                  README_FILE=$(find . -type f -name "README.md" -print -quit)
                  
                  if [[ -z "$README_FILE" ]]; then
                    echo "README.md 파일을 찾을 수 없습니다."
                    exit 1
                  fi
                  
                  # ⭐️ [수정 1] grep 실패 시에도 스크립트가 중단되지 않도록 '|| true' 추가
                  PR_TITLE=$(head -n 1 "$README_FILE" | sed 's/# //g' || true)
                  LINK_SECTION=$(grep '\[문제 링크\]' "$README_FILE" || true)
                  PERF_SECTION=$(grep -A 1 '### 성능 요약' "$README_FILE" || true)
                  CATEGORY_SECTION=$(grep -A 1 '### 분류' "$README_FILE" || true)
                  DATE_SECTION=$(grep -A 1 '### 제출 일자' "$README_FILE" || true)
                  
                  PR_BODY="" # PR 본문을 저장할 변수 초기화
                  
                  # ⭐️ [수정 2] 각 섹션의 내용이 실제로 존재할 때만 PR 본문에 추가
                  if [[ -n "$LINK_SECTION" ]]; then
                    PR_BODY+="${LINK_SECTION}\n\n"
                  fi
                  if [[ -n "$PERF_SECTION" ]]; then
                    PR_BODY+="${PERF_SECTION}\n\n"
                  fi
                  if [[ -n "$CATEGORY_SECTION" ]]; then
                    PR_BODY+="${CATEGORY_SECTION}\n\n"
                  fi
                  if [[ -n "$DATE_SECTION" ]]; then
                    PR_BODY+="${DATE_SECTION}\n"
                  fi
                  
                  # 여러 줄로 된 본문을 GitHub Actions 출력으로 전달
                  {
                    echo 'body<<EOF'
                    echo "${PR_BODY}"
                    echo 'EOF'
                  } >> "$GITHUB_OUTPUT"
                  
                  echo "title=${PR_TITLE}" >> "$GITHUB_OUTPUT"